# This file is part of crest.
# SPDX-Identifier: LGPL-3.0-or-later
#
# crest is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# crest is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with crest.  If not, see <https://www.gnu.org/licenses/>.

srcs += files(
  'fortran_helper.f90',
  'a_angle_derivatives.f90',
  'a_dihedral_derivatives.f90',
  'b_angle_derivatives.f90',
  'b_dihedral_derivatives.f90',
  'c_angle_derivatives.f90',
  'c_dihedral_derivatives.f90',
  'd_dihedral_derivatives.f90',
  'angle_derivatives.f90',
  'bond_derivatives.f90',
  'lj_derivatives.f90',
  'dihedral_derivatives.f90',
  'energy.f90',
  'inv_rij_derivatives.f90',
  'repulsion_derivatives.f90', 
  'analytical_derivatives.f90',
  'ff_utility.f90',
  'ff_interface.f90',
  'grad_derivatives.f90',
  'numerical_derivatives.f90'
)
