[build-system]
requires = ["setuptools>=42", "wheel", "scikit-build", "cmake>=3.18", "ninja", "numpy>=1.21"]
build-backend = "setuptools.build_meta"


[tool.scikit-build.cmake.define]
SKBUILD = "ON"

[project]
name = "ffits"
version = "0.1.0"
description = "Force Field-informed Transition States"
authors = [
    {name = "Daria Babushkina", email = "babushkina@pc.rwth-aachen.de" },
    {name = "Christoph Bannwarth", email = "bannwarth@pc.rwth-aachen.de"}]
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "networkx",
  #"molbar",
  "pandas",
]

[project.optional-dependencies]
dev = ["pytest", ]

[tool.scikit-build]
# This section tells scikit-build-core how to run CMake
cmake.minimum-version = "3.15"
cmake.build-type = "Release"
# Where to put the compiled extensions
wheel.expand-macos-universal-tags = true
sdist.include = ["CMakeLists.txt", "src/"]

# Optional: If your Fortran sources live in src/fortran
[tool.scikit-build.cmake]
source-dir = "src"
build-dir = "_skbuild"
