package:
  name: ffits
  version: 0.9.1

source:
  path: .

build:
  number: 0
  script:
    - python setup.py build_ext --inplace
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - scikit-build
    - cmake
    - ninja
    - gfortran
    - numpy
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - networkx
    - pandas
    - scipy
    - molbar

test:
  imports:
    - ffits
    - ffits.forcefield.fortran.fortran_forcefield
