#This is a CREST input file
input = "struc1.xyz"
runtype = "ancopt"
threads = 4
 
[calculation]
id = 1
maxcycle = 219
 
[[calculation.level]]
method = "ssff"
refgeo = "struc1.xyz"
refhessian = "hess1"
refwbo = "wbo1"
refff = "ff1"
useff = true
 
 
 
 